### ISSUE TITLE
バックグラウンドでリンクを開けるようお願い致します。

### ISSUE THREAD

**Issue by 2ji3150** [sienori/Open-Link-with-New-Tab#2]
アドオンの開発ありがとうございます。
ただ一つの要望があります。
バックグラウンドでリンクを開けるよう設定を追加して欲しいです。
（開いたタブに移動しないでほしい）

**Comment by sienori** [comment]
about:configより以下の設定をtrueにすると実現できます。
browser.tabs.loadDivertedInBackground
